documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'bun.lock'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/**/*'
          - 'public/**/*'
          - '**/*.html'
          - '**/*.css'
          - '**/*.svelte'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.ts'
          - 'index.ts'

services:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/services/**/*'

routes:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/routes/**/*'

middleware:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/middleware/**/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - 'tsconfig.json'
          - '.env.example'
          - '*.config.js'
          - '*.config.ts'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - 'tests/**/*'

ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
